{
  "_from": "@fastify/error@^2.0.0",
  "_id": "@fastify/error@2.0.0",
  "_inBundle": false,
  "_integrity": "sha512-wI3fpfDT0t7p8E6dA2eTECzzOd+bZsZCJ2Hcv+Onn2b7ZwK3RwD27uW2QDaMtQhAfWQQP+WNK7nKf0twLsBf9w==",
  "_location": "/@fastify/error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@fastify/error@^2.0.0",
    "name": "@fastify/error",
    "escapedName": "@fastify%2ferror",
    "scope": "@fastify",
    "rawSpec": "^2.0.0",
    "saveSpec": null,
    "fetchSpec": "^2.0.0"
  },
  "_requiredBy": [
    "/fastify"
  ],
  "_resolved": "https://registry.npmjs.org/@fastify/error/-/error-2.0.0.tgz",
  "_shasum": "a9f94af56eb934f0ab1ce4ef9f0ced6ebf2319dc",
  "_spec": "@fastify/error@^2.0.0",
  "_where": "C:\\Users\\SakhtAfzar\\Desktop\\Node\\fastifyApi\\node_modules\\fastify",
  "author": {
    "name": "Tomas Della Vedova"
  },
  "bugs": {
    "url": "https://github.com/fastify/fastify-error/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "A small utility, used by Fastify itself, for generating consistent error objects across your codebase and plugins.",
  "devDependencies": {
    "@types/node": "^17.0.0",
    "ava": "^3.9.0",
    "standard": "^17.0.0",
    "tsd": "^0.20.0",
    "typescript": "^4.1.3"
  },
  "homepage": "https://github.com/fastify/fastify-error#readme",
  "keywords": [
    "fastify",
    "error",
    "utility",
    "plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "@fastify/error",
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fastify/fastify-error.git"
  },
  "scripts": {
    "test": "standard && ava -v && tsd"
  },
  "tsd": {
    "compilerOptions": {
      "esModuleInterop": true
    }
  },
  "types": "index.d.ts",
  "version": "2.0.0"
}
